export const finFields = [
  { key: 'arrivalTime', value: 'Tuloaika' },
  { key: 'departTime', value: 'Lähtöaika' },
  { key: 'name', value: 'Nimi*' },
  { key: 'email', value: 'Sähköposti*' },
  { key: 'meeting', value: 'Kokouspäivä' },
  { key: 'recreational', value: 'Virkistyspäivä' },
  { key: 'somethingElse', value: 'Muu, mikä?' },
  { key: 'visitType', value: 'Mikä on vierailusi tyyppi?' },
  { key: 'linen', value: 'Lakanat', price: 12 },
  { key: 'towels', value: 'Pyyhkeet', price: 4 },
  { key: 'hottub', value: 'Palju', price: 200 },
  { key: 'sauna', value: 'Sauna', price: 0 },
  { key: 'dayMeeting', value: 'Päiväkokous', duration: 8, price: 580, info: 'lisätietoa' },
  { key: 'dayMeetingSauna', value: 'Päiväkokous ja saunailta', duration: 12, price: 780, info: 'lisätietoa' },
  { key: 'meetingAccommodation', value: 'Kokouspäivä majoituksella', duration: 32, price: 1285, info: 'lisätietoa' },
  { key: 'lunchToLunchAccommodation', value: 'Lounaasta lounaaseen -kokouspäivä majoituksella', duration: 24, price: 0, info: 'lisätietoa' },
  { key: 'meetingType', value: 'Millaisen kokouksen haluat pitää?' },
  { key: 'recreationalType', value: 'Millaisen virkistyspäivän haluat pitää?' },
  { key: 'luonnonLumoa', value: 'Luonnon lumoa', url: 'x' },
  { key: 'liikkumisenIloa', value: 'Liikkumisen iloa', url: 'x' },
  { key: 'villaParatiisi', value: 'Villa Paratiisi (alle 20 hlöä)', url: 'x' },
  { key: 'salmenTupa', value: 'Salmen Tupa', url: 'x' },
  { key: 'nuuksionTupa', value: 'Nuuksion Tupa (yli 20 hlöä)', url: 'x' },
  { key: 'luontoIlmanTiloja', value: 'Luonto ilman tiloja', url: 'x' },
];

export const enFields = [
  { key: 'arrivalTime', value: 'Arrival time' },
  { key: 'departTime', value: 'Departure time' },
  { key: 'name', value: 'Name' },
  { key: 'email', value: 'Email' },
];
